[package]
name = "more-wasm3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm3 = {version = "0.3.1", features = ["build-bindgen"]}